wip

diff --git a/charts/test/templates/configmap.yaml b/charts/test/templates/configmap.yaml
--- a/charts/test/templates/configmap.yaml
+++ b/charts/test/templates/configmap.yaml
@@ -5,11 +5,10 @@ metadata:
   name: sidekick-script
 data:
   openvpn.sh: |
-    #!/bin/bash
+    #!/usr/bin/env bash
     if [[ -f /vpn/vpn_conf.ovpn ]]; then
         rm /vpn/vpn_conf.ovpn
     fi
     touch /vpn/vpn_conf.ovpn
-    curl -Lks /vpn/vpn_conf.ovpn $SIDEKICK_URL > /vpn/vpn_conf.ovpn
-    cat /vpn/vpn_conf.ovpn
+    curl -Lks $SIDEKICK_URL -o /vpn/vpn_conf.ovpn || (echo 'Cannot curl ovpn profile' && exit 1);
     /sbin/tini -s -- /usr/bin/openvpn.sh $@
